name: Update IPTV

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行一次

jobs:
  update-iptv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch IPTV content and remove metadata
      run: |
        # 获取 IPTV 内容并保存
        curl -k 'https://www.now61.com/api/v3/share/content/0l6FA?path=null' \
          -H 'referer: https://www.now61.com/s/0l6FA/text?name=iptv.txt' \
          -o raw_iptv.txt
        
        # 删除包含 '#genre#' 的行和日期行
        sed '/#genre#/d; /^[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}$/d' raw_iptv.txt > iptv.txt

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add iptv.txt
        git commit -m "Update IPTV file"
        git push
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
